#!/bin/bash

clear
echo ' ____  _   _  ____ ____       __  __  ___  _   _ ___ _____ ___  ____'
echo '|  _ \| | | |/ ___|  _ \     |  \/  |/ _ \| \ | |_ _|_   _/ _ \|  _ \'
echo '| | | | |_| | |   | |_) |____| |\/| | | | |  \|  | |  | |  | | | |_) |'
echo '| |_| |  _  | |___|  __/_____| |  | | |_| | |\   | |  | |  |_| |  _ <'
echo '|____/|_| |_|\____|_|        |_|  |_|\___/|_| \_|___| |_| \___/|_| \_\'
echo ""
echo "Made By Japinper        GitHub https://github.com/Japinper/Dhcp_Monitor"
echo ""

#Are you roo?
if [[ $EUID != 0 ]]
then
    echo "You need to be root to execute the script"
    echo ""
    exit
fi

#Menu
echo "[1] Installation"
echo "[2] Help"
echo "[3] Exit"
echo ""
read -r -p "Select an option-> " menu
echo ""

case $menu in
#Option 1
1)
#Service DHCP?
service --status-all | grep "isc-dhcp-server" &>/dev/null
if [[ $? != 0 ]]
then
echo "The service isc-dhcp-server is not installed"
echo "Exiting..."
sleep 0.5
exit
fi

#Service Up
systemctl is-active isc-dhcp-server &>/dev/null

if [[ $? != 0 ]]
then
echo "The service isc-dhcp-service is inactive"
read -r -p "Do you want to start the service?(Y/N)-> " startdhcp
echo ""
    if [[ $startdhcp == "Y" ]] || [[ $startdhcp == "y" ]]
    then
    service isc-dhcp-server start
    echo "Now the service is Up"
    sleep 0.5
    clear
    fi
fi
clear
#Script
echo ""
read -r -p "Do you want to start the installation(Y/N)-> " start

if [[ $start == "Y" ]] || [[ $start == "y" ]]
then
    read -r -p "Select the path to save the files(ex:/home/...)-> " path
    if [[ ! -d $path ]]
    then
        echo "The file path doesn't exist"
        echo "Leaving the installaiton..."   
        sleep 0.5
        exit
    fi

    echo "Running installation..."
    sleep 1
    clear

#Telegram configuration  
    echo "[*] Bot Telegram Configuration..."
    read -r -p "- Chat ID -> " telegram_chat 
    read -r -p "- Bot Token ->" telegram_bot
    echo "[!] Bot Telegram Configuration"
    echo ""

#DHCP.log file
    echo "[*] Creating DHCP.log file..."
    sleep 0.5
    echo "log-facility local1;" >> /etc/dhcp/dhcpd.conf
    echo "local1.info /var/log/dhcp.log" >> /etc/rsyslog.conf 
    
    if [[ ! -c /var/log/dhcp.log ]]
    then
    touch /var/log/dhcp.log
    fi
    echo "For the proper functioning is necessary restart the (dhcp) and (rsyslog) service"
    read -r -p "- Do you want to do now?(Y/N)-> " reboot

    if [[ $reboot == "Y" ]] || [[ $reboot == "y" ]]
    then
        service isc-dhcp-server restart
        service rsyslog restart
    fi
    echo "[!] DHCP.log file created"
    echo ""

#Configuration File
    echo "[*] Creating configuration file"
    if [[ ! -c $path/file.conf ]]
    then
    touch $path/file.conf
    fi
    sleep 0.5
    echo "[!] Configuration file created"
    echo ""
#Signed Ip
    echo "[*] Creating Signed IP file"
    if [[ ! -c $path/signed_ip.txt ]]
    then
    touch $path/signed_ip.txt
    fi
    sleep 0.5
    echo "[!] Signed IP file created"
    echo ""

#DHCP Log
   echo "[*] Creating Dhcp extracted logs file"
    if [[ ! -c $path/dhcp_extracted.txt ]]
    then
    touch $path/dhcp_extracted.txt
    fi
    sleep 0.5
    echo "[!] Dhcp extracted logs file created"
    echo ""

#Crontab
    echo "[*] Creating Crontab task"
    findlogdhcp=$(find / -name Dhcp_extracted)
    echo "* * * * * bash $findlogdhcp" >> /var/spool/cron/crontabs/root
    echo "[!]Crontab task created"
    echo ""

#Commands from bot
read -r -p "Do you want to install a service for send commands with your telegram bot(Y/N)-> " send_telbot
if [[ $send_telbot == "Y" ]] || [[ $send_telbot == "y" ]]
then
echo "[*] Creating service" 
    if [[ ! -c /lib/systemd/system/dhcp_monitor.service ]]
    then
        touch /lib/systemd/system/dhcp_monitor.service
        finddhcpbot=$(find / -name Dhcp_commandbot )
        echo -e "
        [Unit]
        Description=dhcp_monitor
        After=network.target
        StartLimitIntervalSec=0

        [Service]
        Type=simple
        Restart=always
        RestartSec=1
        User=root
        ExecStart=/usr/bin/env bash $finddhcpbot

        [Install]
        WantedBy=multi-user.target" >> /lib/systemd/system/dhcp_monitor.service

        systemctl start dhcp_monitor.service
        systemctl enable dhcp_monitor.service
        systemctl status dhcp_monitor.service | grep "active"
    fi
echo "[!] Service Created"    
fi

sleep 1.5
clear
#File.conf
{
echo "chat_id=$telegram_chat"
echo "token_bot=$telegram_bot"
echo "files_path=$path"

} > $path/file.conf

#Finishing Setup
    echo "Congratulations!!"
    echo "Your script is now configured and redy to be used"
    base64 -d <<< "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICA6PT09PT09PT09PT09PT09PT09PT09OiAgICAgICAKICAgICAgK0BAJSUlJSUlJSUlJSUlJSUlJSUlJUBAKyAgICAgIAogICAgICAjQCogKysrKysrICAgICAtPSAgPS0gKkAjICAgICAgCiAgICAgICNAKi4qKioqKiogICAgID0rLi4rKyAqQCMgICAgICAKICAgICAgI0BAKioqKioqKioqKioqKioqKioqKiVAIyAgICAgIAogICAgICAjQCUrKysrKysrKysrKysrKysrKysrJUAjICAgICAgCiAgICAgICNAKi4lJSUlJSUgICAgICAgICAgICA9IysgICAgICAKICAgICAgI0AjLj09PT09PSAgICAgICAgICAgICAgICAgICAgIAogICAgICAjQEBAQEBAQEBAQEA9ICAgIC4uIC0lQCouIDogICAgCiAgICAgICNAIzotLS0tLS0uLiAgICAtQEBAQEBAQEBAQCMgICAKICAgICAgI0AqLkBAQEBAQCAgICAgIC1AQEAlKz0qQEBAJS4gIAogICAgICAjQCU9PT09PT09PT0uICBAQEBAJSAgICAtQEBAQCogCiAgICAgIDoqJUBAQEBAQEBAQC0gIDorQEBAKzouLSVAQEAtLiAKICAgICAgICAgICAgICAgICAgICAgIDpAQEBAQEBAQEBAIyAgIAogICAgICAgICAgICAgICAgICAgICAgID09LStAQCU9LSs6ICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgIC0tOiAgICAgICAK"
    echo "Thanks for use Dhcp_Monitor          By Japinper"
    sleep 1
    exit

#Principal If
elif [[ $start == "N" ]] || [[ $start == "n" ]]
then
    echo "Exiting..."
    sleep 0.5
fi
;;

#Option 2
2)
clear
echo ' _   _ _____ _     ____'
echo '| | | | ____| |   |  _ \'
echo '| |_| |  _| | |   | |_) |'
echo '|  _  | |___| |___|  __/'
echo '|_| |_|_____|_____|_|'
echo ""
echo "[/] What files save the selected path?"
echo "   - Configuration file"
echo "   - Registered IP"
echo "   - DHCP logs"
echo ""
echo "[/] Telegram Settings"
echo "   - Chat Id -> You can see your chat ID in this BOT https://telegram.me/userinfobot"
echo "   - Token BOT -> You can your BOT token in the BotFather Chat writing /mybots "
echo ""
echo "[/] Crontab"
echo "   - With crontab the task are going to execute every minutes"
echo "   - If crontab does not execute the task write in the terminal (crontab -e and option 1)"
echo ""
echo "[/] Files"
echo "   - Dhcp.log -> This file extract all DHCP logs from syslog /var/log/dhcp.log"
echo "   - file.conf -> This file save all settings"
echo "   - signed_ip.txt -> This file save Ip address - MAC - OSName from the devices connected to DHCP"
echo "   - file.conf -> This file save all settings"
echo "   - dhcp_extracted.txt -> This file contains all the Time - Ip Address - MAC - OSName"   
echo ""
echo " How can I create a Telegram BOT?"
echo " 1. Login in Telegram"
echo " 2. Add to your contacts BotFather https://telegram.me/BotFather"
echo " 3. In the Chat write /start and the BOT will give you the options"
echo " 4. Write /newbot"
echo " 5. Enter the name for your BOT"
echo " 6. Start and enjoy the BOT ;)"
echo ""
;;

#Option 3
3)
echo "Exiting..."
echo "Thanks for use DHCP_MONITOR"
sleep 0.5
exit
;;

esac
